GCC  = g++
FLAGS= -fsanitize=undefined -fsanitize=address -fsanitize=leak

clean:
	rm -rf *.out *~ *.dat *.txt
puntoa:Tambor_a.cpp
	$(GCC) $(FLAGS) Tambor_a.cpp
puntob:Tambor_b.cpp
	$(GCC) $(FLAGS) Tambor_b.cpp
puntoc:Tambor_c.cpp
	$(GCC) $(FLAGS) Tambor_c.cpp
